### ISSUE TITLE
Icon Licensing

### ISSUE THREAD

**Issue by xjzi** [file-icons/icons#104]
Many of these icons seem to be derivative works of icons released under a variety of licenses. For example, from a quick glance the Emacs icon on the Emacs website is licensed under CC BY-SA 4.0.

A. Are these icons original or derivative works?
B. If these icons are derivative works, are they licensed under the respective licenses of their sources?

**Comment by Alhadis** [comment]
> If these icons are derivative works, are they licensed under the respective licenses of their sources?

No, they aren't. Trying to impose a license upon each individual icon would be madness; the entire icon-set is released under the [ISC license](https://github.com/file-icons/icons/blob/51b2231bc06baf1045b538d4d7bf4ade9254eea4/LICENSE.md).

Why do you ask?

**Comment by xjzi** [comment]
Many licenses like the CC BY-SA 4.0 or the GNU GPL don't permit you to relicense derivative works except to a small set of compatible licenses that does not include the ISC license. I ask because I am including a couple of icons from this set into my own set of icons and I wanted to figure out how to license them. It is late here, so I will sort out the rest of the "license hell" later.

**Comment by Alhadis** [comment]
[Copyleft licensing applies to source code, not graphics that've been redrawn by hand](https://wptavern.com/the-gpl-license-doesnt-provide-the-freedom-to-infringe-registered-trademarks#attachment_25392):

> The GPL is a license that defines the terms of use for the code. A license does not serve the same function as a copyright or trademark and the GPL itself is designed for software <b><ins>not for logos or names</ins></b>.

There're also hundreds of permissively-licensed icon projects on GitHub that include logos of GPL-licensed software, so I seriously doubt copyleft restrictions can apply to images. It also wouldn't make sense to enforce the terms of a license meant for source code on an opaque graphic that's distributed in a completely different medium.

**Comment by xjzi** [comment]
As with most legal arguments, I'm dubious that redrawing absolves you of licensing. For your second point, anyone can take anything GPLed and nominally release it to the public domain if they want to but they are at risk of getting in trouble for copyright violation. Also, GPL may be intended for source code but CC licenses are definitely written to cover images.

 In practice, I plan on including the ISC license to satisfy its conditions while licensing it under the GPL, so I won't need you to do anything else.
