### ISSUE TITLE
Icon Request: Minecraft Bedrock Edition Files

### ISSUE THREAD

**Issue by YhvrWasTaken** [file-icons/icons#56]
Basically just some .zips with their extensions changed.

I think some include:
.mclevel
.mcpack
.mcworld

Not quite sure, you might need to look it up.

**Comment by Alhadis** [comment]
Would [the existing Minecraft icon](https://github.com/file-icons/icons/blob/76bd3c4f8b5be540b47771b0d53e6a435425c4c2/svg/Minecraft.svg) suffice?
