### ISSUE TITLE
Icon Request: Noon

### ISSUE THREAD

**Issue by monsterkodi** [file-icons/icons#58]
Hello, it would be nice if an icon for [noon](https://github.com/monsterkodi/noon) could be included.
I tried to attach the svg, but it didn't let me :-( I packaged it in a zip instead.
Please let me know if I need to do something else.
[Noon.zip](https://github.com/file-icons/icons/files/3537595/Noon.zip)

**Comment by Alhadis** [comment]
Hey mate, 👋

You can embed the SVG's source directly using a fenced code-block. E.g.:

~~~markdown
```svg
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="512px" height="512px">
	…
</svg>
```
~~~

**Comment by monsterkodi** [comment]
Oh, good to know. Thanks for the info and for including the icon.
