### ISSUE TITLE
Add vyper icon

### ISSUE THREAD

**Issue by 6ry0u** [file-icons/icons#60]
Hi,

Could you add [this new icon](https://raw.githubusercontent.com/ethereum/vyper/master/logo/vyper-logo-transparent.svg?sanitize=true) for [vyper](https://github.com/ethereum/vyper) files?
```
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" id="Transparent_Logo" viewBox="0 0 2048 1773.62">
  <title>vyper-logo-transparent</title>
  <polygon points="1024 886.81 768 1330.22 768 1330.22 1024 1773.62 1280 1330.22 1280 1330.22 1024 886.81" style="opacity:0.8"/>
  <polygon points="1280 443.41 1024 886.81 1024 886.81 1280 1330.22 1536 886.81 1536 886.81 1280 443.41" style="opacity:0.6"/>
  <polygon points="768 443.41 512 886.81 512 886.81 768 1330.22 1024 886.81 1024 886.81 768 443.41" style="opacity:0.6"/>
  <polygon points="1536 0 1280 443.41 1280 443.41 1536 886.81 1792 443.41 1792 443.41 1536 0" style="opacity:0.45"/>
  <polygon points="1152 221.7 896 221.7 768 443.41 768 443.41 1024 886.81 1280 443.41 1152 221.7" style="opacity:0.45"/>
  <polygon points="512 0 256 443.41 256 443.41 512 886.81 768 443.41 768 443.41 512 0" style="opacity:0.45"/>
  <polygon points="1792 443.4 2048 0 1536 0 1792 443.4" style="opacity:0.3"/>
  <polygon points="256 443.4 512 0 0 0 256 443.4" style="opacity:0.3"/>
</svg>
```

**Comment by Alhadis** [comment]
Erm, that's going to be hard. Is there a solid-coloured variant anywhere? The transparency will be impossible to replicate as a font glyph.

Also, what filetypes/file-extensions are we adding this icon to, if any? `.vyper`…?

**Comment by 6ry0u** [comment]
file extensions are `.vy`
What about these files for the icon:
https://github.com/ethereum/vyper/tree/master/logo

**Comment by Alhadis** [comment]
Same problem, I'm afraid. The "flat" variants are simply opaque instead of translucent. The most distinctive feature of the logo is something we can't capture with solid shapes:

<div align="center"><img src="https://user-images.githubusercontent.com/2346707/66881271-1a21a180-f012-11e9-9387-7b7d00c184f2.png" alt="Figure 1" width="500" /></div>

I tried with negative space, but ehhh, even that doesn't look right... 😕

<div align="center"><img src="https://user-images.githubusercontent.com/2346707/66884179-17c44500-f01c-11e9-9999-f5a7d38cfc5d.png" alt="Figure 2" width="500" /></div>

I don't know... Which do you prefer?

**Comment by 6ry0u** [comment]
Hi,
Ok I am not going to take that decision on my own. Let me ask the Vyper Community what they think about the icon choice and your design suggestions.
Thanks already!

**Comment by Alhadis** [comment]
I literally just finished this design, too:

<img width="256" src="https://user-images.githubusercontent.com/2346707/66899788-46a3e080-f047-11e9-8f3b-c004bc451a36.png" alt="Figure 1" width="400" />

I think it works better than the broken solid fill, personally. :+1: Be sure to ask them about that one, too.

**Comment by 6ry0u** [comment]
Hi,
Ok the community spoke!
Let’s go with the middle one
![logo](https://user-images.githubusercontent.com/2346707/66884179-17c44500-f01c-11e9-9999-f5a7d38cfc5d.png)

If it doesn’t look good in the end because the tiles are small, we thought about merging some:
![logo2](https://files.gitter.im/ethereum/vyper/r9kg/image.png)

**Comment by Alhadis** [comment]
LTGM. Thanks for your patience!
