### ISSUE TITLE
Suggestion: Truffle js

### ISSUE THREAD

**Issue by ghivert** [file-icons/icons#61]
Hello !

The `truffle.js` file at the root of any Truffle project is desperately a yellow JS icon. :(
Could you add it to the package ? [Here's the site](https://www.trufflesuite.com/) and [this looks like the icon we're looking for](https://github.com/trufflesuite/trufflesuite.com/blob/master/src/img/truffle-logomark.svg).

Thanks !

**Comment by Alhadis** [comment]
I've added an icon, but it may be a while until it appears in a new release. I've put the project on-hold momentarily until loose ends have been tied up elsewhere.
