### ISSUE TITLE
Icon request: Dhall files

### ISSUE THREAD

**Issue by ghivert** [file-icons/icons#62]
Hello!

Thanks again for the hard work. `.dhall` files dont have icons. Do you think you can add them? [Here's the link to the official icon.](https://github.com/dhall-lang/dhall-lang/blob/master/img/dhall-icon.svg)

Thank you very much!

**Comment by Alhadis** [comment]
Grrr, shortly after a pushed a [release](https://github.com/file-icons/atom/releases/tag/v2.1.37), too. 😂 I've added it, but as I said last time, it might be a while until another release is cut. 😉
