### ISSUE TITLE
Icon Request: Next.js

### ISSUE THREAD

**Issue by SnO2WMaN** [file-icons/icons#63]
Hello!

Icon [Next.js](https://nextjs.org/) for `next.config.js`, etc.

## Source
https://github.com/simple-icons/simple-icons/blob/master/icons/next-dot-js.svg 

from [simple-icons/simple-icons](https://github.com/simple-icons/simple-icons) (CC0)

**Comment by Alhadis** [comment]
> `next.config.js`, etc.

Could you please elaborate on the "etc" part? What other filenames apart from `next.config.js` should I map the icon to?

**Comment by SnO2WMaN** [comment]
I'm sorry, because I didn't investigate in detail, I wrote "etc" because I thought that `next.config.ts` could be used (like `nuxt.config.ts`), but apparently it couldn't be used (https://github.com/zeit/next.js/issues/5318), so please ignore it.
