### ISSUE TITLE
Icon Request: .releaserc[.(ya?ml|js(on)?)]?

### ISSUE THREAD

**Issue by bennypowers** [file-icons/icons#64]
Howdy

[semantic-release](https://github.com/semantic-release/semantic-release) has a [config file schema](https://semantic-release.gitbook.io/semantic-release/usage/configuration)

And they even have a logo!

![logo](https://spectrum.imgix.net/communities/ed22feb2-d0d6-4997-a460-7ca4e182c366/2c7e7d92-ac86-44af-a706-6640f0251030-32174276.png?w=256&h=256&dpr=2&auto=compress&expires=1580169600000&ixlib=js-1.3.0&s=483f4cfab03ca8321267eb0d6e4a465d)

Please consider adding this icon to the list.

**Comment by Alhadis** [comment]
How's this...?

<img src="https://user-images.githubusercontent.com/2346707/73259344-b8c9bb00-421b-11ea-89d2-e275acc313e7.jpg" />

(I'm sorry, I'll get to it…)

**Comment by bennypowers** [comment]
![veruca salt](https://media.giphy.com/media/vO8F4fYQd39h6/giphy.gif)

TYVM
