### ISSUE TITLE
Icon Request: Lefthook

### ISSUE THREAD

**Issue by SnO2WMaN** [file-icons/icons#65]
Icon Request for [Arkweid/lefthook](https://github.com/Arkweid/lefthook), powerful git hook manager like [lint-staged](https://github.com/okonet/lint-staged) & [husky](https://github.com/typicode/husky).

## Resource
https://github.com/Arkweid/lefthook/blob/master/logo_sign.svg

## Assigned files
- `lefthook.yml`
- `lefthook-local.yml`

**Comment by Alhadis** [comment]
Done, thank you!

**Comment by SnO2WMaN** [comment]
Sorry to trouble you, but could you change it to an icon that filled the icon? I think it ’s a bit hard to see…

![image](https://user-images.githubusercontent.com/15155608/75189287-376d3600-5791-11ea-8d21-33e3b060249c.png)
(Icon on My VSCode)

**Comment by Alhadis** [comment]
Ugh, I came within an inch of using a solid-filled variant before deciding the "hollow" one was visually closer to the original image. I've added an alternative icon in cd5ddd1.

**Comment by SnO2WMaN** [comment]
Thanks!
