### ISSUE TITLE
Icon request : Bare Python

### ISSUE THREAD

**Issue by bersace** [file-icons/icons#66]
Hi,

Would it be possible to have bare python logo ? There is `Config` and `Test`, but that would be great to have bare Python like there is for PHP, GO, etc.

Here is the link to official page for Python logo https://www.python.org/community/logos/

Regards,

**Comment by Alhadis** [comment]
The Python icon is already included by the [Mfixx font](https://github.com/file-icons/MFixx/blob/master/charmap.md#Python) (codepoint: `U+F14C`).

This is what I meant about the project's history being messy and chaotic...

**Comment by bersace** [comment]
Thanks for the information.
