### ISSUE TITLE
karma.conf.cjs and pals

### ISSUE THREAD

**Issue by bennypowers** [file-icons/icons#67]
`"type": "module"` is a thing in node-land now, so people like me are going to be doing a lot of `mv karma.conf.js karma.conf.cjs`

Would be swell if we got to keep our icons, too.

Please consider updating regexps to include `cjs` versions of files like `karma.conf.js`

**Comment by Alhadis** [comment]
> `"type": "module"` is a thing in node-land now

Don't worry, [I know](https://github.com/Alhadis/Utils/commit/c084ba9d31620e9fbcbd21725e7b129ea2644fa7). 😉
