### ISSUE TITLE
Icon request: Shadow CLJS

### ISSUE THREAD

**Issue by ghivert** [file-icons/icons#68]
Hi!

Another icon request for me for a new tool I'm using with my favorite languages: [shadow-cljs](https://shadow-cljs.github.io/docs/UsersGuide.html) (with [GitHub link](https://github.com/thheller/shadow-cljs)). 😁

There’s an icon for it: [Icon link](https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/cljs/devtools/server/web/resources/img/shadow-cljs.png)

It's for one file at root of projects called `shadow-cljs.edn`. Right now it has icon of EDN (which is fine) but the Shadow CLJS icon would be awesome!

Thank you very much for your hard work!

**Comment by Alhadis** [comment]
Done. Hope this looks okay, as I'm about to cut a long-overdue release.
