### ISSUE TITLE
Add dart icon

### ISSUE THREAD

**Issue by ericdallo** [file-icons/icons#69]
Lang: https://dart.dev/
Icon: https://dart.dev/assets/shared/dart/logo+text/horizontal/white-e71fb382ad5229792cc704b3ee7a88f8013e986d6e34f0956d89c453b454d0a5.svg
File types: .dart

Thanks

**Comment by ericdallo** [comment]
It looks like the icon already exists [here](https://github.com/file-icons/DevOpicons/blob/master/svg/dart.svg), should we add it here too?

**Comment by Alhadis** [comment]
> should we add it here too?

Why would we do that?

**Comment by ericdallo** [comment]
I want to add `dart` files support to the `all-the-icons.el`(https://github.com/domtronn/all-the-icons.el/pull/201)

**Comment by Alhadis** [comment]
I recommend adding DevOpIcons to the `all-the-icons` package instead. We don't add icons to this font if they're already present in another bundled font.

Ideally we'd put everything into one huge mega-font, but an unfortunate accident of history prevents us from doing that...
