### ISSUE TITLE
Commitlint icon

### ISSUE THREAD

**Issue by matteobertoldo** [file-icons/icons#72]
Hy 👋 is it possible to insert the `commitlint` icon? Here is the reference: https://commitlint.js.org/#/

The files to be targeted, according to the official [setup](https://commitlint.js.org/#/guides-local-setup) should be: `commitlint.config.js` `.commitlintrc.js`, `.commitlintrc.json`. `.commitlintrc.yml`, 
I also found the official icon 😊: https://commitlint.js.org/assets/icon.svg

Thanks so much!

**Comment by Alhadis** [comment]
Done and done! Though I've had to exaggerate the metrics in order for the letterforms to be visible, and even then they're barely legible. 😢

<img src="https://user-images.githubusercontent.com/2346707/81402169-3cc50480-9174-11ea-9def-eaec9ad1f315.png" alt="Figure 1" />

(It might look better on a high-density screen; I'm forced to use an ancient MacBook without a Retina display…)

**Comment by matteobertoldo** [comment]
@Alhadis thank u so much dude! I will try it as soon as available in the next release ❤️

**Comment by Alhadis** [comment]
[Enjoy!](https://github.com/file-icons/atom/releases/tag/v2.1.41) 😀
