### ISSUE TITLE
Icon request: F# files

### ISSUE THREAD

**Issue by ezemtsov** [file-icons/icons#73]
Hi, thanks a lot for your work!

Would it be considerable to add icons `.fs`, `.fsi` and `.fsx` files?
Icon could be taken from the front page of the official site [here](https://fsharp.org/)

**Comment by Alhadis** [comment]
Hi @ezemtsov,

We already have an icon for F#, but it's in [another icon-font](https://github.com/file-icons/DevOpicons/blob/master/charmap.md#e6a7).

**Comment by ezemtsov** [comment]
@Alhadis the problem is related to all-the-icons and discussed many times before.
Thanks again, I'm closing the feature request.
