### ISSUE TITLE
Add LGTM logo for lgtm.yml configuration file

### ISSUE THREAD

**Issue by ericcornelissen** [file-icons/icons#74]
I was wondering if the LGTM logo could be added to the font so that the `lgtm.yml` configuration file (as far as I can tell [that's the only allowed name](https://lgtm.com/help/lgtm/configuring-lgtm-analysis-project)) can be supported by [file-icons](https://github.com/file-icons/atom). There is [an SVG of the logo](https://lgtm.com/static/site/assets/svg-compiled/svg-13eb9ee1.svg) available, for inspiration on how to make it monochrome you could look at [the LGTM logo in Simple Icons](https://simpleicons.org/?q=lgtm).

**Comment by Alhadis** [comment]
Done. Sorry for the slow response; to say life's been hectic recently would be a creative understatement.

**Comment by ericcornelissen** [comment]
Not a problem at all, thanks for adding it :smile:
