### ISSUE TITLE
Add icon for .yamllint files

### ISSUE THREAD

**Issue by mondeja** [file-icons/icons#77]
[`yamllint`](https://github.com/adrienverge/yamllint) is a Python package that allows to lint YAML files. I've seen that `markdownlint` has his own icon for `.markdownlint` files, even if the icon is not official. So I suggest to include an icon for [`.yamllint` configuration files](https://yamllint.readthedocs.io/en/stable/configuration.html#configuration). Maybe adding a check for an existent YAML icon could be enough.

**Comment by Alhadis** [comment]
Would this be adequate?

<img src="https://user-images.githubusercontent.com/2346707/93389622-beaa0480-f8af-11ea-814c-bf61f92ace8d.png" alt="Figure 1" width="250" />

(Sorry about the long wait…)

**Comment by mondeja** [comment]
Thank you!
