### ISSUE TITLE
Icon Request: Calva

### ISSUE THREAD

**Issue by yegortimoshenko** [file-icons/icons#80]
Calva is a Clojure extension for VS Code. It uses `*.calva-repl` files. Here's the project's SVG logo: https://github.com/BetterThanTomorrow/calva/blob/master/assets/images/calva-symbol-logo.svg

**Comment by Alhadis** [comment]
Done! Sorry about the slow response.

**Comment by yegortimoshenko** [comment]
Thanks! :)
