### ISSUE TITLE
Add support for GraphQL Code Generator config file

### ISSUE THREAD

**Issue by ajotaos** [file-icons/icons#84]
GraphQL Code Generator works with a config file `codegen.yaml` or `codegen.json`. Please add support to these files, currently the default JSON and YAML icons are appearing.

**Comment by Alhadis** [comment]
Damn. That was a hell of a lot harder to get looking right than I expected. 😰 The funnel in particular was murder.

**Comment by ajotaos** [comment]
Amazing, thank you 👍
