### ISSUE TITLE
Icon Request: Environment Variables

### ISSUE THREAD

**Issue by ZohebMOPO** [file-icons/icons#91]
Can we add one icon for .env files?. If yes, then I would love to make a PR of this icon.

P.S. I do have the SVG format of the icon. Just let me know how can I add this icon to the source code

**Comment by Alhadis** [comment]
I'm reluctant to add purely-textual icons that aren't official—especially if they repeat the format's name or file extension(s).

Though I'm not averse to adding an icon for `.env` files, it would need to be pictorial instead of textual.

**Comment by ZohebMOPO** [comment]
So If I work on a pictorial logo. Is that ok? @Alhadis

**Comment by Alhadis** [comment]
What exactly do you have in mind?

**Comment by ZohebMOPO** [comment]
The logo of `.env` files is textual.
At first, I coded the Textual SVG logo only.
After that, you replied `it would need to be pictorial instead of textual`. So I am thinking of making a pictorial logo instead of the textual logo. So what u say? Should I go for it?

**Comment by Alhadis** [comment]
Wait, never mind, I just noticed the logo you linked to originally [actually _is_ official](https://github.com/motdotla/dotenv/blob/ba6b34d3c418a633b4c62c8669e48d63bc2b20cd/dotenv.png):

<img src="https://raw.githubusercontent.com/motdotla/dotenv/ba6b34d3c418a633b4c62c8669e48d63bc2b20cd/dotenv.png" alt=".env" />

In that case, it'll need to be treated as canonical. As for adding the SVG, it's a process I prefer to handle myself. [More on that here](https://github.com/file-icons/icons#why-request-an-icon-cant-i-submit-a-pr).

**Comment by Alhadis** [comment]
@ZohebMOPO File Icons isn't like most open source projects. It has less to do with code than it does graphics—and graphical skills aren't something that coders are expected to have.

In other words, this project isn't a common or realistic example of most open source projects. 😉 Just leave things to me, I'll get around to adding the icon later tonight.
